license:
  header: |
    This file is part of llctl.
    Copyright © 2016 Donovan Solms.
    Project Limitless
    https://www.projectlimitless.io

    llctl and Project Limitless is free software: you can redistribute it and/or modify
    it under the terms of the Apache License Version 2.0.

    You should have received a copy of the Apache License Version 2.0 with
    llctl. If not, see http://www.apache.org/licenses/LICENSE-2.0.
